name: Build Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lowercase repository owner
      shell: bash
      run: echo "LOWERCASE_REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Extract CNI_PLUGINS_VERSION from Dockerfile
      shell: bash
      run: echo "CNI_PLUGINS_VERSION=$(grep -oP '(?<=ARG CNI_PLUGINS_VERSION=)[^ ]+' Dockerfile)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
            ghcr.io/${{ env.LOWERCASE_REPO_OWNER }}/install-cni-bundle:latest
            ghcr.io/${{ env.LOWERCASE_REPO_OWNER }}/install-cni-bundle:${{ env.CNI_PLUGINS_VERSION }}
        platforms: linux/amd64
        file: Dockerfile
        context: .
